FamilyStorage/FamilyStorage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from FamilyStorage.views import (
    UserDelete, UserInfoView, UserUpdate, connections_page, main_page, sign_up
)

urlpatterns = [
    path('', main_page, name='main_page'),
    path('admin/', admin.site.urls),
    path('connections/', connections_page, name='connections'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('sign_up/', sign_up, name='sign_up'),
    path('account/', UserInfoView.as_view(), name='account'),
    path('account/update/', UserUpdate.as_view(), name='update_user'),
    path('account/delete/', UserDelete.as_view(), name='delete_user'),
]

urlpatterns += [
    path('people/', include('Person.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FamilyStorage/Person/urls.py
from django.urls import path

from Person.views import download, PersonCreate, PersonDelete, PersonInfoView, PersonListView

urlpatterns = [
    path('', PersonListView.as_view(), name='all_people'),
    path('add/', PersonCreate.as_view(), name='add_person'),
    path('<int:pk>/', PersonInfoView.as_view(), name='person_info'),
    path('<int:pk>/delete/', PersonDelete.as_view(), name='delete_person'),
    path('<int:pk>/download/', download, name='download_person_info'),
]

FamilyStorage/Person/models.py
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify
from django.core.exceptions import ValidationError


def photo_file_name(instance, *args, **kwargs):
    photo_type = ''

    if args:
        uploaded_file = args[0]
        uploaded_type = uploaded_file.partition('.')[2]
        if uploaded_type:
            photo_type = uploaded_type

    return f'photos/{slugify(str(instance))}.{photo_type}'


def validate_image(image):
    file_size = image.file.size
    limit_mb = 20
    if file_size > limit_mb * 1024 * 1024:
        raise ValidationError(f"Max size of file is {limit_mb} MB")


class PersonModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=150, default='')
    last_name = models.CharField(max_length=150, default='', blank=True)
    patronymic = models.CharField(max_length=150, default='', blank=True)
    gender = models.CharField(max_length=6, blank=True,
                              choices=[('Male', 'Male'), ('Female', 'Female')])
    date_of_birth = models.DateField(null=True, blank=True, help_text='DD/MM/YYYY')
    date_of_death = models.DateField(null=True, blank=True, help_text='DD/MM/YYYY')
    info = models.TextField(max_length=2000, default='', blank=True)
    place_of_birth = models.CharField(max_length=150, default='', blank=True)
    place_of_death = models.CharField(max_length=150, default='', blank=True)
    mother = models.ForeignKey("self", on_delete=models.SET_NULL, null=True, blank=True,
                               related_name='mother_children')
    father = models.ForeignKey("self", on_delete=models.SET_NULL, null=True, blank=True,
                               related_name='father_children')
    photo = models.ImageField(upload_to=photo_file_name, null=True, blank=True,
                              validators=[validate_image])  # TODO: remove not used images

    class Meta:
        ordering = ["last_name", "first_name"]

    ADDITIONAL_FIELDS = ['siblings', 'children']

    def __str__(self):
        res = self.first_name
        res += f' {self.patronymic}' if self.patronymic else ''
        res += f' {self.last_name}' if self.last_name else ''
        return res

    def get_absolute_url(self):
        return reverse('person_info', args=[self.id])

    @property
    def siblings(self):
        siblings = set()

        if self.mother:
            siblings.update([person for person in self.mother.mother_children.all()])
        if self.father:
            siblings.update([person for person in self.father.father_children.all()])

        return [person for person in siblings if person != self]

    @property
    def children(self):
        children = set()
        children.update([person for person in self.mother_children.all()])
        children.update([person for person in self.father_children.all()])
        return list(children)

    def get_data(self) -> dict:
        data = {f.verbose_name: getattr(self, f.attname) for f in self._meta.concrete_fields}
        for field in self.ADDITIONAL_FIELDS:
            data[field] = getattr(self, field, None)

        not_to_show = ['ID', 'user']
        for field in not_to_show:
            if field in data:
                del data[field]

        to_str = ['date of birth', 'date of death']
        for field in to_str:
            if field in data:
                data[field] = str(data.get(field) or '')

        person_id_to_str_name = ['mother', 'father']
        for field in person_id_to_str_name:
            needed_id = data.get(field)
            if needed_id:
                data[field] = str(PersonModel.objects.get(id=needed_id))

        if data.get('photo'):  # TODO: change hardcode
            data['photo'] = data['photo'].path

        return data

FamilyStorage/Person/forms.py
from django import forms

from FamilyStorage import settings
from Person.models import PersonModel


class PersonModelForm(forms.ModelForm):
    date_of_birth = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS,
                                    help_text='DD/MM/YYYY', required=False)
    date_of_death = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS,
                                    help_text='DD/MM/YYYY', required=False)

    def __init__(self, *args, **kwargs):
        super(PersonModelForm, self).__init__(*args, **kwargs)
        if 'initial' in kwargs:
            user = kwargs['initial'].get('user')
            person = kwargs['initial'].get('event')  # TODO

            mother_queryset = PersonModel.objects.filter(user=user)
            if person:
                mother_queryset = mother_queryset.exclude(id=person.id)
            self.fields['mother'].queryset = mother_queryset

            father_queryset = PersonModel.objects.filter(user=user)
            if person:
                father_queryset = father_queryset.exclude(id=person.id)
            self.fields['father'].queryset = father_queryset

    class Meta:
        model = PersonModel
        fields = '__all__'

FamilyStorage/Person/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, FormMixin
from django.forms.models import model_to_dict

from FamilyStorage.settings import MEDIA_DIR, STATIC_DIR
from Person.forms import PersonModelForm
from Person.helpers import get_pdf_name
from Person.models import PersonModel
from django.http import FileResponse, HttpResponse, HttpResponseRedirect


class PersonInfoView(FormMixin, LoginRequiredMixin, generic.detail.DetailView):
    template_name = 'person_info.html'
    model = PersonModel
    context_object_name = 'person'
    form_class = PersonModelForm

    def get(self, request, *args, **kwargs):
        response = super(PersonInfoView, self).get(request, *args, **kwargs)

        self.request.session['post_name'] = ''
        self.request.session['object_id'] = response.context_data['object'].id
        self.request.session['edit_data'] = []

        if request.user == response.context_data['object'].user:
            return response
        else:
            return redirect(reverse('main_page'))

    def get_success_url(self):
        return reverse("person_info", args=[self.get_object().id])

    def get_context_data(self, **kwargs):
        ctx = super(PersonInfoView, self).get_context_data(**kwargs)
        ctx["form"] = self.get_form()
        ctx["post_name"] = self.request.session.get('post_name')
        ctx["object_id"] = self.request.session.get('object_id')
        ctx["edit_data"] = self.request.session.get('edit_data')
        return ctx

    def get_initial(self):
        return ({"event": self.get_object(), 'user': self.request.user})

    def post(self, request, *args, **kwargs):
        req_keys = list(request.POST.keys())

        self.object = self.get_object()

        edit_data = [i.replace('edit__', '') for i in req_keys if 'edit__' in i]
        if edit_data:
            request.session['post_name'] = 'edit'
            request.session['object_id'] = self.object.id
            request.session['edit_data'] = edit_data
            return redirect(reverse("person_info", args=[self.object.id]))

        data = model_to_dict(self.object)
        data.update(request.POST.dict())
        files = request.FILES.dict()

        form = self.form_class(data, files, instance=self.object)

        delete_data = [i.replace('delete__', '') for i in req_keys if 'delete__' in i]
        for field in delete_data:
            field_data = getattr(form.instance, field)
            if field_data:
                (MEDIA_DIR / str(field_data)).unlink(missing_ok=True)
            field_data.delete()

        request.session['post_name'] = 'field'
        request.session['object_id'] = self.object.id
        request.session['edit_data'] = []

        if form.is_valid():
            form.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class PersonListView(LoginRequiredMixin, generic.ListView):
    model = PersonModel
    context_object_name = 'people_list'
    template_name = 'people_list.html'

    def get_queryset(self):
        return PersonModel.objects.filter(user__exact=self.request.user.id)

    @staticmethod
    def post(req, *args, **kwargs):
        if req.POST.get('search'):
            person_url = req.POST.get('person_url')
            if person_url:
                return HttpResponseRedirect(person_url)
        return HttpResponseRedirect(reverse_lazy('all_people'))


class PersonCreate(LoginRequiredMixin, CreateView):
    model = PersonModel
    form_class = PersonModelForm

    def post(self, request, *args, **kwargs):
        data = request.POST

        _mutable_old_state = data._mutable
        data._mutable = True
        data['user'] = request.user
        data._mutable = _mutable_old_state

        return super().post(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.initial.update({'user': request.user})
        return super().get(request, *args, **kwargs)


class PersonDelete(LoginRequiredMixin, DeleteView):
    model = PersonModel
    success_url = reverse_lazy('all_people')


def download(request, pk):
    person = PersonModel.objects.get(id=pk)
    pdf_link = get_pdf_name(str(person), person.get_data())

    link = MEDIA_DIR / f'pdf/{pdf_link}'
    if link.is_file():
        response = FileResponse(open(link, 'rb'))
        return response
    else:
        return HttpResponse('<h3>Can not to create file</h3>')

FamilyStorage/Person/templates/Person/personmodel_confirm_delete.html
{% extends "main_template.html" %}

{% block content %}

<p>Are you sure you want to delete?</p>

<form action="" name="confirm" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

FamilyStorage/Person/templates/Person/personmodel_form.html
{% extends "main_template.html" %}
{% block title %}Add person{% endblock %}

{% block content %}
    <style>
        .list {
            color: #000000;
            font-size: medium;
        }

        .livesearch {
            width: 350px;
        }

        td {
            font-size: 20px;
            line-height: 36px;
            font-weight: bold;
            padding-left: 20px;
        }

        table {
            margin: auto;
            width: 100%;
        }

    </style>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.5.1/chosen.min.css">

    <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
        {% csrf_token %}

    <table>
    <tr>
    <td style="padding-top: 20px; padding-left: 100px; padding-right: 20px;">

    <!--        user        -->
    {{ form.user.as_hidden }}

    <p>{{ form.first_name.label_tag }}
    {{ form.first_name }}

    <p>{{ form.last_name.label_tag }}
    {{ form.last_name }}

    <p>{{ form.patronymic.label_tag }}
    {{ form.patronymic }}

    <p>{{ form.gender.label_tag }}
    {{ form.gender }}

    <p>{{ form.date_of_birth.label_tag }}
    <input type="text" name="date_of_birth" id="id_date_of_birth" placeholder="DD/MM/YYYY">

    <p>{{ form.place_of_birth.label_tag }}
    {{ form.place_of_birth }}

    <p>{{ form.date_of_death.label_tag }}
    <input type="text" name="date_of_death" id="id_date_of_death" placeholder="DD/MM/YYYY">

    <p>{{ form.place_of_death.label_tag }}
    {{ form.place_of_death }}
    <p><input type="submit" value="Create" /></p>
    </td>

    <td style="padding-top: 20px; padding-left: 20px; padding-right: 20px; vertical-align: top;">

    <p>{{ form.info.label_tag }}
    <textarea name="info" cols="50" rows="10"></textarea>

    <p>{{ form.photo.label_tag }}
    {{ form.photo }}

    <p>{{ form.mother.label_tag }}
    <select class="livesearch" name="mother" id={{ form.mother.id_for_label }}>
        {% for i in form.mother %}
            <option class="list" value={{ i.data.value|stringformat:'s' }}>
                {{i.choice_label}}
            </option>
        {% endfor %}
    </select>

    <p>{{ form.father.label_tag }}
    <select class="livesearch" name="father" id={{ form.father.id_for_label }}>
        {% for i in form.father %}
            <option class="list" value={{ i.data.value|stringformat:'s' }}>
                {{i.choice_label}}
            </option>
        {% endfor %}
    </select>

    </td>
    </tr>
    </table>
    </form>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.5.1/chosen.jquery.min.js"></script>

    <script type="text/javascript">
        $(".livesearch").chosen();
    </script>

    <!-- Fengyuan Chen's Datepicker -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css"
          integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE="
          crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js"
            integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k="
            crossorigin="anonymous"></script>

    <script>
        $(function () {
            $( "#id_date_of_birth" ).datepicker({
                format:'dd/mm/yyyy',
            });

            $( "#id_date_of_death" ).datepicker({
                format:'dd/mm/yyyy',
            });
        });
    </script>
{% endblock %}